language: generic
sudo: required
services: 
  - docker

before_install:
  - docker build -t ducbin021/docker-react -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ducbin021/docker-react npm run test

after_success: 
  - docker build -t ducbin021/multi-client ./client
  - docker build -t ducbin021/multi-server ./server 
  - docker build -t ducbin021/multi-worker ./worker 
  - docker build -t ducbin021/multi-nginx ./nginx 
  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push to docker hub
  - docker push ducbin021/multi-client
  - docker push ducbin021/multi-server
  - docker push ducbin021/multi-nginx
  - docker push ducbin021/multi-worker

# deploy:
#   provider: elasticbeanstalk
#   region: "us-east-2"
#   app: "docker"
#   env: "Docker-env"
#   bucket_name: "elasticbeanstalk-us-east-2-240621839480"
#   bucket_path: "elasticbeanstalk-us-east-2-240621839480"
#   on:
#     branch: master
#   access_key_id: "$AWS_ACCESS_KEY"
#   secret_access_key: "$AWS_SECRET_KEY"
